### ISSUE TITLE
Borrow some ideas into deanius:promise ?

### ISSUE THREAD

**Issue by deanius** [arsnebula/reactive-promise#2]
Hi - I see some cool things in here - the ability to label and reactively check the resolution status of the promise. Just wanted to let you know I may either point people to this package, or absorb functionality in to mine.. Are you still actively developing ?

**Comment by chrismbeckett** [comment]
Borrow away :) That's the beauty of open-source. Not actively developing for Meteor anymore, but this package is stable.
